# -*- mode: ruby -*-
# vi: set ft=ruby :

$shell_script = <<SCRIPT
  Write-Host "Hey, this happened after the restart!"
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "mfellows/windows2012r2"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  # Run Windows Domain Provisioner
  config.vm.provision :windows_domain do |domain|

    # The Windows Domain to join.
    #
    # Setting this will result in an additional restart.
    domain.domain = "domain.int"

    # The new Computer Name to use when joining the domain.
    #
    # Uses the Rename-Computer PowerShell command. ORRRR -NewName flag??
    # Specifies a new name for the computer in the new domain.
    domain.computer_name = "myfandangledname"

    # The Username to use when authenticating against the Domain.
    #
    # Specifies a user account that has permission to join the computers to a new domain. 
    domain.username = "me"

    # The Password to use when authenticating against the Domain.
    #
    # Specifies the password of a user account that has permission to 
    # join the computers to a new domain. 
    domain.password = "iprobablyshouldntusethisfield"

    # An array of advanced options to pass when joining the Domain.
    #
    # See (https://technet.microsoft.com/en-us/library/hh849798.aspx) for detail.
    # NOTE: If we user :computer_name from above this needs to be merged!!
    # domain.join_options = ['Win9xUpgrade']

    # Organisational Unit path in AD.
    #
    # Specifies an organizational unit (OU) for the domain account. 
    # Enter the full distinguished name of the OU in quotation marks. 
    # The default value is the default OU for machine objects in the domain.
    # domain.ou_path = nil

    # Performs an unsecure join to the specified domain.
    #
    # When this option is used username/password are not required
    domain.unsecure = false
  end

  # Confirm that this will run after the reload from the domain provisioner!
  config.vm.provision "shell", inline: $shell_script  
end
